name: Build Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix git ownership check
        run: git config --global --add safe.directory '*'

      - name: Compile firmware
        run: make epomaker/galaxy100_lite:via

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: galaxy100_lite_firmware
          path: |
            *.bin
            *.hex
